# Generated by Django 3.2.4 on 2021-08-01 01:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default='yhswwpam97nojmgryvcm', max_length=255, verbose_name='image'),
        ),
    ]
