# Generated by Django 3.2.4 on 2021-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='lesson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='profile',
            field=models.IntegerField(),
        ),
    ]
